export const GET_MOVIE = 'GET_MOVIE';
export const GET_GENRES = 'GET_GENRES';
export const GENRES_SORT = 'GENRES_SORT';
export const CHANGE_CURRENT_PAGE = 'CHANGE_CURRENT_PAGE';
export const CHANGE_MAIN_INPUT = 'CHANGE_MAIN_INPUT';
export const MOVIE_SEARCH = 'MOVIE_SEARCH';
export const CHANGE_THEME = 'CHANGE_THEME';
